export const COUNTRIES: { country: string; flag: string }[] = [
  { country: 'Afghanistan', flag: '🇦🇫' },
  { country: 'Albania', flag: '🇦🇱' },
  { country: 'Algeria', flag: '🇩🇿' },
  { country: 'Andorra', flag: '🇦🇩' },
  { country: 'Angola', flag: '🇦🇴' },
  { country: 'Argentina', flag: '🇦🇷' },
  { country: 'Armenia', flag: '🇦🇲' },
  { country: 'Australia', flag: '🇦🇺' },
  { country: 'Austria', flag: '🇦🇹' },
  { country: 'Azerbaijan', flag: '🇦🇿' },
  { country: 'Bahrain', flag: '🇧🇭' },
  { country: 'Bangladesh', flag: '🇧🇩' },
  { country: 'Barbados', flag: '🇧🇧' },
  { country: 'Belarus', flag: '🇧🇾' },
  { country: 'Belgium', flag: '🇧🇪' },
  { country: 'Benin', flag: '🇧🇯' },
  { country: 'Bhutan', flag: '🇧🇹' },
  { country: 'Bolivia', flag: '🇧🇴' },
  { country: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { country: 'Botswana', flag: '🇧🇼' },
  { country: 'Brazil', flag: '🇧🇷' },
  { country: 'Brunei', flag: '🇧🇳' },
  { country: 'Bulgaria', flag: '🇧🇬' },
  { country: 'Burkina Faso', flag: '🇧🇫' },
  { country: 'Burundi', flag: '🇧🇮' },
  { country: 'Cambodia', flag: '🇰🇭' },
  { country: 'Cameroon', flag: '🇨🇲' },
  { country: 'Canada', flag: '🇨🇦' },
  { country: 'Cape Verde', flag: '🇨🇻' },
  { country: 'Central African Republic', flag: '🇨🇫' },
  { country: 'Chad', flag: '🇹🇩' },
  { country: 'Chile', flag: '🇨🇱' },
  { country: 'China', flag: '🇨🇳' },
  { country: 'Colombia', flag: '🇨🇴' },
  { country: 'Comoros', flag: '🇰🇲' },
  { country: 'Congo', flag: '🇨🇬' },
  { country: 'Costa Rica', flag: '🇨🇷' },
  { country: 'Croatia', flag: '🇭🇷' },
  { country: 'Cuba', flag: '🇨🇺' },
  { country: 'Cyprus', flag: '🇨🇾' },
  { country: 'Czechia', flag: '🇨🇿' },
  { country: 'Czech Republic', flag: '🇨🇿' },
  { country: 'Denmark', flag: '🇩🇰' },
  { country: 'Djibouti', flag: '🇩🇯' },
  { country: 'Dominica', flag: '🇩🇲' },
  { country: 'Dominican Republic', flag: '🇩🇴' },
  { country: 'Ecuador', flag: '🇪🇨' },
  { country: 'Egypt', flag: '🇪🇬' },
  { country: 'El Salvador', flag: '🇸🇻' },
  { country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { country: 'Estonia', flag: '🇪🇪' },
  { country: 'Eswatini', flag: '🇸🇿' },
  { country: 'Ethiopia', flag: '🇪🇹' },
  { country: 'Fiji', flag: '🇫🇯' },
  { country: 'Finland', flag: '🇫🇮' },
  { country: 'France', flag: '🇫🇷' },
  { country: 'Gabon', flag: '🇬🇦' },
  { country: 'Gambia', flag: '🇬🇲' },
  { country: 'Georgia', flag: '🇬🇪' },
  { country: 'Germany', flag: '🇩🇪' },
  { country: 'Ghana', flag: '🇬🇭' },
  { country: 'Greece', flag: '🇬🇷' },
  { country: 'Grenada', flag: '🇬🇩' },
  { country: 'Guatemala', flag: '🇬🇹' },
  { country: 'Guinea', flag: '🇬🇳' },
  { country: 'Guinea-Bissau', flag: '🇬🇼' },
  { country: 'Guyana', flag: '🇬🇾' },
  { country: 'Haiti', flag: '🇭🇹' },
  { country: 'Honduras', flag: '🇭🇳' },
  { country: 'Hungary', flag: '🇭🇺' },
  { country: 'Iceland', flag: '🇮🇸' },
  { country: 'India', flag: '🇮🇳' },
  { country: 'Indonesia', flag: '🇮🇩' },
  { country: 'Iran', flag: '🇮🇷' },
  { country: 'Iraq', flag: '🇮🇶' },
  { country: 'Ireland', flag: '🇮🇪' },
  { country: 'Israel', flag: '🇮🇱' },
  { country: 'Italy', flag: '🇮🇹' },
  { country: 'Ivory Coast', flag: '🇨🇮' },
  { country: 'Jamaica', flag: '🇯🇲' },
  { country: 'Japan', flag: '🇯🇵' },
  { country: 'Jordan', flag: '🇯🇴' },
  { country: 'Kazakhstan', flag: '🇰🇿' },
  { country: 'Kenya', flag: '🇰🇪' },
  { country: 'Kosovo', flag: '🇽🇰' },
  { country: 'Kuwait', flag: '🇰🇼' },
  { country: 'Kyrgyzstan', flag: '🇰🇬' },
  { country: 'Laos', flag: '🇱🇦' },
  { country: 'Latvia', flag: '🇱🇻' },
  { country: 'Lebanon', flag: '🇱🇧' },
  { country: 'Lesotho', flag: '🇱🇸' },
  { country: 'Liberia', flag: '🇱🇷' },
  { country: 'Libya', flag: '🇱🇾' },
  { country: 'Liechtenstein', flag: '🇱🇮' },
  { country: 'Lithuania', flag: '🇱🇹' },
  { country: 'Luxembourg', flag: '🇱🇺' },
  { country: 'Madagascar', flag: '🇲🇬' },
  { country: 'Malawi', flag: '🇲🇼' },
  { country: 'Malaysia', flag: '🇲🇾' },
  { country: 'Maldives', flag: '🇲🇻' },
  { country: 'Mali', flag: '🇲🇱' },
  { country: 'Malta', flag: '🇲🇹' },
  { country: 'Mauritania', flag: '🇲🇷' },
  { country: 'Mauritius', flag: '🇲🇺' },
  { country: 'Mexico', flag: '🇲🇽' },
  { country: 'Moldova', flag: '🇲🇩' },
  { country: 'Monaco', flag: '🇲🇨' },
  { country: 'Mongolia', flag: '🇲🇳' },
  { country: 'Montenegro', flag: '🇲🇪' },
  { country: 'Morocco', flag: '🇲🇦' },
  { country: 'Mozambique', flag: '🇲🇿' },
  { country: 'Myanmar', flag: '🇲🇲' },
  { country: 'Namibia', flag: '🇳🇦' },
  { country: 'Nepal', flag: '🇳🇵' },
  { country: 'Netherlands', flag: '🇳🇱' },
  { country: 'New Zealand', flag: '🇳🇿' },
  { country: 'Nicaragua', flag: '🇳🇮' },
  { country: 'Niger', flag: '🇳🇪' },
  { country: 'Nigeria', flag: '🇳🇬' },
  { country: 'North Korea', flag: '🇰🇵' },
  { country: 'North Macedonia', flag: '🇲🇰' },
  { country: 'Norway', flag: '🇳🇴' },
  { country: 'Oman', flag: '🇴🇲' },
  { country: 'Pakistan', flag: '🇵🇰' },
  { country: 'Palestine', flag: '🇵🇸' },
  { country: 'Panama', flag: '🇵🇦' },
  { country: 'Papua New Guinea', flag: '🇵🇬' },
  { country: 'Paraguay', flag: '🇵🇾' },
  { country: 'Peru', flag: '🇵🇪' },
  { country: 'Philippines', flag: '🇵🇭' },
  { country: 'Poland', flag: '🇵🇱' },
  { country: 'Portugal', flag: '🇵🇹' },
  { country: 'Qatar', flag: '🇶🇦' },
  { country: 'Romania', flag: '🇷🇴' },
  { country: 'Russia', flag: '🇷🇺' },
  { country: 'Rwanda', flag: '🇷🇼' },
  { country: 'Saudi Arabia', flag: '🇸🇦' },
  { country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { country: 'Senegal', flag: '🇸🇳' },
  { country: 'Serbia', flag: '🇷🇸' },
  { country: 'Seychelles', flag: '🇸🇨' },
  { country: 'Sierra Leone', flag: '🇸🇱' },
  { country: 'Singapore', flag: '🇸🇬' },
  { country: 'Slovakia', flag: '🇸🇰' },
  { country: 'Slovenia', flag: '🇸🇮' },
  { country: 'Somalia', flag: '🇸🇴' },
  { country: 'South Africa', flag: '🇿🇦' },
  { country: 'South Korea', flag: '🇰🇷' },
  { country: 'South Sudan', flag: '🇸🇸' },
  { country: 'Spain', flag: '🇪🇸' },
  { country: 'Sri Lanka', flag: '🇱🇰' },
  { country: 'Sudan', flag: '🇸🇩' },
  { country: 'Suriname', flag: '🇸🇷' },
  { country: 'Sweden', flag: '🇸🇪' },
  { country: 'Switzerland', flag: '🇨🇭' },
  { country: 'Syria', flag: '🇸🇾' },
  { country: 'Taiwan', flag: '🇹🇼' },
  { country: 'Tajikistan', flag: '🇹🇯' },
  { country: 'Tanzania', flag: '🇹🇿' },
  { country: 'Thailand', flag: '🇹🇭' },
  { country: 'Timor-Leste', flag: '🇹🇱' },
  { country: 'Togo', flag: '🇹🇬' },
  { country: 'Trinidad and Tobago', flag: '🇹🇹' },
  { country: 'Tunisia', flag: '🇹🇳' },
  { country: 'Turkey', flag: '🇹🇷' },
  { country: 'Turkmenistan', flag: '🇹🇲' },
  { country: 'Uganda', flag: '🇺🇬' },
  { country: 'Ukraine', flag: '🇺🇦' },
  { country: 'United Arab Emirates', flag: '🇦🇪' },
  { country: 'United Kingdom', flag: '🇬🇧' },
  { country: 'United States', flag: '🇺🇸' },
  { country: 'Uruguay', flag: '🇺🇾' },
  { country: 'Uzbekistan', flag: '🇺🇿' },
  { country: 'Venezuela', flag: '🇻🇪' },
  { country: 'Vietnam', flag: '🇻🇳' },
  { country: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { country: 'Yemen', flag: '🇾🇪' },
  { country: 'Zambia', flag: '🇿🇲' },
  { country: 'Zimbabwe', flag: '🇿🇼' },
];

export function flagForNationality(nationality?: string): string | undefined {
  if (!nationality) return undefined;
  const norm = nationality.trim().toLowerCase();
  const exact = COUNTRIES.find(c => c.country.toLowerCase() === norm);
  if (exact) return exact.flag;
  const partial = COUNTRIES.find(c => c.country.toLowerCase().includes(norm) || norm.includes(c.country.toLowerCase()));
  return partial?.flag;
}

export function flagForCountry(country: string): string | undefined {
  return flagForNationality(country);
}

export function countryCodeFor(nationality?: string): string | undefined {
  const flag = flagForNationality(nationality);
  if (!flag) return undefined;
  const cps = [...flag].map(ch => ch.codePointAt(0)!);
  if (cps.length === 2 && cps[0] >= 0x1F1E6 && cps[0] <= 0x1F1FF && cps[1] >= 0x1F1E6 && cps[1] <= 0x1F1FF) {
    return String.fromCharCode(cps[0] - 0x1F1E6 + 65) + String.fromCharCode(cps[1] - 0x1F1E6 + 65);
  }
  return undefined;
}
